version: '3' 

services:
  app:
    build: .
    ports:
      - "8500:8500"
    environment:
      - SERVER=${SERVER}
      - DATABASE=${DATABASE}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
    volumes:
      - .:/app
    networks:
      - appnet

networks:
  appnet:
